phpbbireland_portal_controller:
    pattern: /portal.php
    defaults: { _controller: phpbbireland.portal.main:display }


# Not yet supported #
#phpbbireland_portal_controller:
#    pattern: /portal/page/{page}
#    defaults: { _controller: phpbbireland.portal.main:display, page: "portal" }
#    requirements:
#        page:        \d+

# Redirect to portal by default
#phpbbireland_portal_redirect_controller:
#    pattern: /
#    defaults: { _controller: phpbbireland.portal.main:display }

phpbbireland_portal_redirect_controller:
    pattern: /rules.php
    defaults: { _controller: phpbbireland.portal.main:rules }
